main_region        = "us-east-1"
project_name       = "two-tier"
environment        = "dev"
my_ip              = "203.0.113.42/32"
public_key_path    = "~/.ssh/id_rsa.pub"
notification_email = "devops-dev@example.com"
